return {
	-- ["project"] = "user.github.io", (project.luau.page CNAME record for user.github.io/project)
	[""] = "nicell.github.io",
	["_acme-challenge.discord"] = "3f40ea0a64b37d2b233b05cbb98b7861._acme.deno.net.",
	["discord"] = "alias.deno.net",
	["hermes"] = "froststarinteractive.github.io",
	["lynx"] = "lynx-luau.pages.dev",
	["playfab"] = "grilme99.github.io",
	["purse"] = "ryanlua.github.io",
	["react"] = "jsdotlua.github.io",
	["rocket"] = "teamfireworks.github.io",
	["satchel"] = "ryanlua.github.io",
	["sentry"] = "grilme99.github.io",
	["typeforge"] = "typeforge-luau.github.io",
	["ui-labs"] = "pepeeltoro41.github.io",
}
